<?php
/**
 * This class represents the exceptional circumstance where a user
 * with an expired password attempts to access LORIS.
 *
 * PHP Version 5
 *
 * @category Errors
 * @package  Loris
 * @author   Dave MacFarlane <david.macfarlane2@mcgill.ca>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

/**
 * The PasswordExpiredException class.
 *
 * @category Errors
 * @package  Loris
 * @author   Dave MacFarlane <david.macfarlane2@mcgill.ca>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

class PasswordExpiredException extends LorisException
{
}
?>
