name: LORIS Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Printing PHP Version
      run: php --version

    - name: Install OS package dependencies
      # run: sudo apt-get install nodejs-dev node-gyp libssl1.0-dev npm php-pear php7.4-dev php7.4-cli
      run: sudo apt-get install php-ast

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Build LORIS
      run: make dev

  checkstatic:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Lint PHP
      run: npm run lint:php
    - name: Phan
      run: vendor/bin/phan
    - name: Lint Javascript
      run: npm run lint:javascript
